FROM nvcr.io/nvidia/pytorch:25.04-py3


WORKDIR /home/root/

RUN git clone https://github.com/dsuess/nunchaku -b dev --recursive

WORKDIR /home/root/nunchaku

RUN NUNCHAKU_SM_TARGETS=86 python setup.py develop
